// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Q0oEuM8AXQtUxrgsXET1kz22IbwXxy8',
    appId: '1:736731624790:web:3fc00ef412addba682d2f7',
    messagingSenderId: '736731624790',
    projectId: 'iitd-oae-b9687',
    authDomain: 'iitd-oae-b9687.firebaseapp.com',
    storageBucket: 'iitd-oae-b9687.firebasestorage.app',
    measurementId: 'G-2GQ8EDWD93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYvyNn_7S_2Km_CkxTICrfMr8h-DvqSnM',
    appId: '1:736731624790:android:b1dc207c39bf84f482d2f7',
    messagingSenderId: '736731624790',
    projectId: 'iitd-oae-b9687',
    storageBucket: 'iitd-oae-b9687.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_hixiLOIxMnuCDnUjLrJvyvo4zrzG28',
    appId: '1:736731624790:ios:fb9005a81b3fc57482d2f7',
    messagingSenderId: '736731624790',
    projectId: 'iitd-oae-b9687',
    storageBucket: 'iitd-oae-b9687.firebasestorage.app',
    iosBundleId: 'com.iitd.oae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_hixiLOIxMnuCDnUjLrJvyvo4zrzG28',
    appId: '1:736731624790:ios:b5c0ab98d5d07bd482d2f7',
    messagingSenderId: '736731624790',
    projectId: 'iitd-oae-b9687',
    storageBucket: 'iitd-oae-b9687.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Q0oEuM8AXQtUxrgsXET1kz22IbwXxy8',
    appId: '1:736731624790:web:5b79b49f4becc92282d2f7',
    messagingSenderId: '736731624790',
    projectId: 'iitd-oae-b9687',
    authDomain: 'iitd-oae-b9687.firebaseapp.com',
    storageBucket: 'iitd-oae-b9687.firebasestorage.app',
    measurementId: 'G-QW09HTEYYT',
  );

}